// Copy third-party browser bundles from node_modules into assets/js/vendor/
// so pages can <script src> them without a CDN and without a JS bundler.
// Output is gitignored and regenerated by the build (npm run build / CI).
import { mkdirSync, copyFileSync } from "node:fs";
import { dirname } from "node:path";

const COPIES = [
  ["node_modules/chart.js/dist/chart.umd.min.js", "assets/js/vendor/chart.umd.min.js"],
];

for (const [src, dest] of COPIES) {
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  console.log(`vendored ${src} -> ${dest}`);
}
